### ISSUE TITLE
[CSS] Navigation bar items are out of reach when in extreme zoom

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#30]
![Repro](https://dl.dropboxusercontent.com/u/8522559/personal-jekyll-theme/bugs/bug.PNG)

When zoomed in a lot (i.e. 675%) from a desktop browser, the items in the navigation bar are not accessible in the lower part of the list.

Should the navigation list for mobile be scrollable?

@joariasl CSS champion, any ideas/inputs on this? :smile:

**Comment by joariasl** [comment]
A posible solution is add this rules for .navbar-custom in CSS:
```css
.navbar-custom {
    ...
    max-height: 100%;
    overflow-y: auto;
}
```

I will finish best when I have time.
